---
title: "Chapter 4: EDA"
author: "Cory Lanker"
output: html_notebook
---

Much of the following code is from Wickham's Mastering Shiny, Chapter 4.

```{r setup}
library(vroom)
library(tidyverse)
```

Download data and save in new `neiss` directory:
```{r load-data}
dir.create("neiss")
#> Warning in dir.create("neiss"): 'neiss' already exists
download <- function(name) {
  url <- "https://github.com/hadley/mastering-shiny/raw/master/neiss/"
  download.file(paste0(url, name), paste0("neiss/", name), quiet = TRUE)
}
download("injuries.tsv.gz")
download("population.tsv")
download("products.tsv")
```

```{r}
(injuries <- vroom::vroom("neiss/injuries.tsv.gz"))
```

```{r}
(products <- vroom::vroom("neiss/products.tsv"))
(population <- vroom::vroom("neiss/population.tsv"))
```

## Exploration
```{r}
selected <- injuries %>% filter(prod_code == 649)
nrow(selected)

(selected %>% count(location, wt = weight, sort = TRUE))
(selected %>% count(body_part, wt = weight, sort = TRUE))
(selected %>% count(diag, wt = weight, sort = TRUE))
```

```{r}
(summary <- selected %>% 
  count(age, sex, wt = weight))
summary %>% 
  ggplot(aes(age, n, colour = sex)) + 
  geom_line() + 
  stat_smooth() +
  labs(y = "Estimated number of injuries")
```

Same plot but now based on per 10k
```{r}
(summary <- selected %>% 
  count(age, sex, wt = weight) %>% 
  left_join(population, by = c("age", "sex")) %>% 
  mutate(rate = n / population * 1e4))
summary %>% 
  ggplot(aes(age, rate, color = sex)) + 
  geom_line() + 
  stat_smooth() +
  labs(y = "Estimated number of injuries per 10k")
```

